{% set version = "0.3.4" %}

package:
  name: jaconv
  version: {{ version }}

source:
  url: https://github.com/ikegami-yukino/jaconv/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bc5b1869a85f82dd26c62977012615c16ddfe5330685cc938905f481534c9e09

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - nose
    - python {{ python_min }}
  source_files:
    - test_jaconv.py
  imports:
    - jaconv
  commands:
    - nosetests test_jaconv

about:
  home: https://ikegami-yukino.github.io/jaconv/jaconv.html
  license: MIT
  license_file: LICENSE
  summary: Pure-Python Japanese character interconverter for Hiragana, Katakana, Hankaku, and Zenkaku
  dev_url: https://github.com/ikegami-yukino/jaconv

extra:
  recipe-maintainers:
    - h-vetinari
